# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Flutter version from pubspec
      run: |
        set -e

        brew install yq
        _flutterVersion=$( yq read pubspec.yaml environment.flutter )
        echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
#        channel: stable
#    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pip install requests
    - run: python test_upload.py ${{ secrets.token }}
